CREATE TABLE `biz_user` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户ID，主键，自增',
  `app_id` bigint DEFAULT NULL COMMENT '所属应用ID',
  `auth_type` tinyint NOT NULL COMMENT '区分用户登录类型，0游客 1手机验证码 2阿里一键 3微信',
  `oaid` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备标识符(ch主流安卓设备标识OAID）',
  `device_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备标识，oaid优先否则deviceId',
  `wechat_user_id` bigint DEFAULT NULL COMMENT '微信登录方式，用户id标识',
  `mobile_user_id` bigint DEFAULT NULL COMMENT '手机号验证码登录方式，用户id标识',
  `nickname` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `avatar_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `real_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `id_card` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ip` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `device_model` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '设备型号',
  `channel` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '渠道',
  `mobile` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '手机号，默认为空',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_valid` tinyint NOT NULL DEFAULT '1' COMMENT '逻辑删除标记，1有效0无效',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_user_app_auth_oaid_device_valid` (`app_id`,`auth_type`,`oaid`,`device_id`,`is_valid`),
  KEY `idx_biz_user_app_id` (`app_id`),
  KEY `idx_biz_user_auth_type` (`auth_type`),
  KEY `idx_biz_user_valid` (`is_valid`),
  CONSTRAINT `fk_biz_user_biz_app` FOREIGN KEY (`app_id`) REFERENCES `biz_app` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表，存储用户信息';